name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"

jobs:
  build-and-push:
    uses: aaronkyriesenbach/workflows/.github/workflows/docker-build-push.yml@master
    with:
      package-json-path: package.json
    permissions:
      contents: read
      packages: write
